let movies = [{
    id:1,
    title:'Spider-man No Way Home',
    rating: 10,
    awards: 5,
    length: 180,
    price: 1500,
    genre:'Acción',
},
{    id:2,
    title:'Misterio a bordo',
    rating: 7,
    awards: 1,
    length: 110,
    price: 800,
    genre:'Comedia',
},
{    id:3,
    title:'Mi vecino totoro',
    rating: 9,
    awards:3,
    length:100,
    price:1000,
    genre:'Animación',
},
{    id:4,
    title:'Farenheit 451',
    rating:10,
    awards:10,
    length:90,
    price:700,
    genre:'Ciencia ficción',
},
{
    id:5,
    title:'Blackjack 21',
    rating:10,
    awards:1,
    length:190,
    price:1300,
    genre:'Aventuras',
}]

module.exports = movies